### ISSUE TITLE
Can't install on debian 9.5 stable/stretch

### ISSUE THREAD

**Issue by Benjalien** [im-0/cometblue#10]
Hi
(and first of all thanks for all your efforts!)
I cant get Cometblue to install on my Debian 9.5 :(
Here's what I get:
root@rack:/home/benjalien/Downloads/pygattlib# pip install cometblue
Requirement already satisfied: cometblue in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: click in /usr/lib/python2.7/dist-packages (from cometblue)
Collecting gattlib (from cometblue)
  Using cached https://files.pythonhosted.org/packages/be/2f/5b1aecec551b42b59d8b399ad444b5672972efb590ca83d784dbe616a3e1/gattlib-0.20150805.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-SzpHky/gattlib/setup.py", line 12, in <module>
        "pkg-config --cflags glib-2.0".split()).decode('utf-8')
      File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SzpHky/gattlib/

From what I understand I can't get gattlib to install.
Any hint?

Thanks!
Benjamin

**Comment by Benjalien** [comment]
Hi myself,
just in case someon else would have the issue: here's how I finally solved it: https://community.home-assistant.io/t/new-ha-0-27-and-bluetooth-le-tracker/3336/12
Enjoy!
