### ISSUE TITLE
Doesn't work on latest Debian, gattlib exception

### ISSUE THREAD

**Issue by Code7R** [im-0/cometblue#13]
Traceback (most recent call last):
  File "/usr/local/bin/cometblue", line 6, in <module>
    from cometblue.cli import main
  File "/usr/local/lib/python3.9/dist-packages/cometblue/cli.py", line 17, in <module>
    import cometblue.device
  File "/usr/local/lib/python3.9/dist-packages/cometblue/device.py", line 10, in <module>
    import gattlib
SystemError: initialization of gattlib raised unreported exception

Compiled on Debian Unstable. Also had to investigate which deps gattlib has, which isn't documented here unfortunately.
(which are: libboost-thread-dev libboost-python-dev libbluetooth-dev)

# strace -f cometblue 2>&1 | grep -i gatt
newfstatat(AT_FDCWD, "/usr/local/lib/python3.9/dist-packages/gattlib.cpython-39-x86_64-linux-gnu.so", {st_mode=S_IFREG|0755, st_size=4930568, ...}, 0) = 0
openat(AT_FDCWD, "/usr/local/lib/python3.9/dist-packages/gattlib.cpython-39-x86_64-linux-gnu.so", O_RDONLY|O_CLOEXEC) = 3

# python3 -V
Python 3.9.9

**Comment by maschhoff** [comment]
Hi I just forked that project, I faced the same issues some years ago. I have some notes maybe they will help.
I think the best way is to run this in a docker to resolv that dependencies and not changing them in the host system.
I run it on a raspi.

![image](https://user-images.githubusercontent.com/4007829/148443564-1ffd48d6-761e-4f7d-8359-af91d109e444.png)
